# Generated by Django 5.0.2 on 2025-03-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=50)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("chunk_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="QueryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField()),
                ("response_text", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "documents_retrieved",
                    models.ManyToManyField(
                        related_name="queries", to="rag_api.document"
                    ),
                ),
            ],
        ),
    ]
